### ISSUE TITLE
Wrong header on tty login

### ISSUE THREAD

**Issue by eliasbakken** [goeland86/ReFactor#13]
The greeting/header shown when logging in via tty0 looks a bit off: 

```
# BEGIN ANSIBLE MANAGED BLOCK
"ReFactor 1.0.0-RC1

Check that nothing is printing before any intensive operation!
"
# END ANSIBLE MANAGED BLOCK
```

Needs updating.

**Comment by goeland86** [comment]
Hmm. Yes. I'm thinking I want to try and automate the use of the git tag or checkout to identify the version that's running.

Need to see what the best way to do that is.

**Comment by goeland86** [comment]
@eliasbakken on the next few builds of ReFactor can you check and let me know if this is fixed? I have too little time to do the checks myself at the moment.
