### ISSUE TITLE
Pin aliases not working

### ISSUE THREAD

**Issue by IAnolastname** [goeland86/ReFactor#18]
For whatever reason, pin aliases do not work. In RC4, it should be THERM_E, THERM_BED, THERM_H by the pin aliases.

However, Klipper only acknowledges them as host:analog4, host:analog6, host:analog5.

**Comment by IAnolastname** [comment]
Oh, and this is just for anyone who reads this and runs into the issues I had, but for multiple Z steppers, you cannot have different Z settings for different motors beyond pins and step distance under RC4. In older versions, it was okay.

**Comment by goeland86** [comment]
I need to fix this by opening a PR upstream. Will reference it when I submit the PR there.

**Comment by goeland86** [comment]
Was fixed upstream on Klipper: https://github.com/KevinOConnor/klipper/pull/3420
